version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mi_basedatos
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: contraseña
    networks:
      - springnet

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mi_basedatos
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contraseña
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    networks:
      - springnet

networks:
  springnet:
